name: Build and deploy Node.js app to Azure Web App - AbastoExpressPWA

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Requerido para actions/checkout
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'
      
      # Instalación de Yarn si es necesario
      - name: Install Yarn
        run: npm install -g yarn

      - name: Yarn install, build, and test
        run: |
          yarn install --frozen-lockfile
          yarn build

      # Instalamos 'serve' para que esté disponible en la carpeta node_modules
      - name: Install necessary runtime server package
        run: yarn add serve --dev
        
      # 🚀 CORRECCIÓN 1: Creamos un script de inicio más robusto
      # Ahora apunta directamente al binario 'serve' dentro de node_modules
      - name: Create Azure Startup Script
        run: |
          echo 'node ./node_modules/serve/bin/serve.js -s dist -l 8080' > startup.sh
          chmod +x startup.sh

      # 🚀 CORRECCIÓN 2: Subimos la carpeta node_modules completa
      # Esto garantiza que 'serve' y todas sus dependencias estén disponibles en Azure
      - name: Cleanup and Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            dist
            startup.sh
            package.json
            yarn.lock
            node_modules/ # ✅ Subimos el directorio completo
            

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Requerido para solicitar el JWT para Azure login
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: . # Descarga todos los archivos, incluyendo node_modules y startup.sh

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_15616D1BC0A54364ACDD1B2306E70DC7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_707D3FC0E54D47DF8CFF53AFA22F604E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BD6889BFEB024B1BA8D235604E199458 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AbastoExpressPWA'
          slot-name: 'Production'
          package: . # Despliega la carpeta actual, que contiene 'dist', 'node_modules' y 'startup.sh'
