name: Build and deploy Node.js app to Azure Web App - AbastoExpressPWA

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'
      
      # ⚠️ NO necesitas 'npm install -g yarn' si ya lo estás usando en los siguientes pasos,
      # 'actions/setup-node@v4' suele configurarlo. Lo dejo por si tu proyecto lo requiere.
      - name: Install Yarn
        run: npm install -g yarn

      - name: Yarn install, build, and test
        run: |
          yarn install --frozen-lockfile # Mejor práctica para CI
          yarn build

      # ⚠️ La instalación de 'serve' como --dev está bien, pero para que Azure la use en la runtime,
      # lo más seguro es tratarla como una dependencia normal o de dev/peer si el build lo necesita.
      # Ya que solo se usa para servir el BUILDEADO, es una dependencia de runtime de despliegue.
      # La dejo como está, pero la clave está en el ARTEFACTO.
      - name: Install necessary runtime server package
        run: yarn add serve --dev
        
      # El script de inicio es CORRECTO
      - name: Create Azure Startup Script
        run: |
          # ⚠️ Uso de 'npx' requiere que 'node_modules' esté en el PATH.
          # Como subiremos 'node_modules', esto debería funcionar.
          echo 'npx serve -s dist -l 8080' > startup.sh
          chmod +x startup.sh

      - name: Cleanup and Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            dist
            startup.sh
            package.json
            yarn.lock
            # 🚀 ¡CAMBIO CLAVE! Incluye todo el directorio 'node_modules'.
            # Esto asegura que 'serve' y sus dependencias estén disponibles para el 'npx' en Azure.
            node_modules/ 
          # ⚠️ Nota: Podrías necesitar agregar un archivo `.deployment` o especificar
          # un directorio raíz en el paso de 'azure/webapps-deploy@v3' si tu app no está en la raíz.
          # Por ahora, confiamos en que tu 'dist' está bien.

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: . # Descarga en el directorio raíz del job de despliegue

      - name: Login to Azure
        # ... (Tu configuración de Azure Login)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_15616D1BC0A54364ACDD1B2306E70DC7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_707D3FC0E54D47DF8CFF53AFA22F604E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BD6889BFEB024B1BA8D235604E199458 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AbastoExpressPWA'
          slot-name: 'Production'
          package: . # Despliega el contenido de la carpeta actual
