# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - AbastoExpressPWA

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      # --- PASO DE DIAGNÓSTICO ---
      - name: List files for debugging
        run: ls -al

      - name: Set up Node.js version
        # Utiliza la versión 4 de setup-node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          # Añadimos cache: 'yarn' para optimizar la instalación
          cache: 'yarn'

      # Instalamos Yarn globalmente
      - name: Install Yarn
        run: npm install -g yarn

      - name: Yarn install, build, and test
        # Usamos Yarn para evitar el error de Rollup/dependencias opcionales de npm
        run: |
          yarn install
          yarn build
          # yarn test --if-present (Mantener si tienes tests, lo quito por simplicidad)

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          # CORRECCIÓN CLAVE 1: Sube solo la carpeta 'dist'
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          # El artifact 'node-app' ahora contiene la carpeta 'dist'
          
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_15616D1BC0A54364ACDD1B2306E70DC7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_707D3FC0E54D47DF8CFF53AFA22F604E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BD6889BFEB024B1BA8D235604E199458 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AbastoExpressPWA'
          slot-name: 'Production'
          # CORRECCIÓN CLAVE 2: Despliega la carpeta 'dist' que está dentro del artefacto descargado
          package: dist
